name: Run with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker images
        run: docker-compose build
      - name: Start the services and then shut them down
        run: |
          docker-compose up -d
          docker-compose down
      - name: Run the automated backend tests
        run: docker run --rm interseco_backend pytest
