name: Run with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and run tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the Docker images
        run: docker-compose build
      - name: Start the services
        run: docker-compose up -d
      - name: Run the automated front end tests
        run: docker run interseco_frontend npm test
      - name: Run the automated back end tests
        run: docker run interseco_backend pytest
      - name: Shut down the services
        run: docker-compose down
